// <auto-generated />
namespace Trpz2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class Added_PriceField_To_SpecialOffer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_PriceField_To_SpecialOffer));
        
        string IMigrationMetadata.Id
        {
            get { return "201911300837379_Added_PriceField_To_SpecialOffer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
